// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB13d-i5lWWEmciIGwBVVXOc-ISdmcp5OA',
    appId: '1:241659510315:web:dfb162e83251c73b2fb46e',
    messagingSenderId: '241659510315',
    projectId: 'signup-cabf5',
    authDomain: 'signup-cabf5.firebaseapp.com',
    storageBucket: 'signup-cabf5.appspot.com',
    measurementId: 'G-YPNF1WGKE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhwf-7Bj7zoa_zk7LTkGzQiz6bNwNnZ0',
    appId: '1:241659510315:android:90dd71149f80e2fc2fb46e',
    messagingSenderId: '241659510315',
    projectId: 'signup-cabf5',
    storageBucket: 'signup-cabf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaWjR-2sWEKhJym39cVanA-knpvKNYo0',
    appId: '1:241659510315:ios:cffb675a7d84f0122fb46e',
    messagingSenderId: '241659510315',
    projectId: 'signup-cabf5',
    storageBucket: 'signup-cabf5.appspot.com',
    iosClientId: '241659510315-thdf1apsfbf0m5g8jnbfunebhve88hdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaWjR-2sWEKhJym39cVanA-knpvKNYo0',
    appId: '1:241659510315:ios:cffb675a7d84f0122fb46e',
    messagingSenderId: '241659510315',
    projectId: 'signup-cabf5',
    storageBucket: 'signup-cabf5.appspot.com',
    iosClientId: '241659510315-thdf1apsfbf0m5g8jnbfunebhve88hdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
